### ISSUE TITLE
Blocking ads No effect

### ISSUE THREAD

**Issue by rrn21833** [guardianproject/orbot-apple#35]

**Comment by tladesignz** [comment]
Sorry, but this short sentence is not exactly helpful.

I'll try to imagine some things, but I won't be able to help you further, if you don't come up with more info.

1. The content blocker of Orbot is not really an ad blocker. For that we would need to convert and maintain huge public filter lists for which we don't have the resources. It's just a little tool you can play around with yourself to e.g. block all foreign fonts, websites try to load, or block that one little annoying thing.

2. You need to activate it explicitly in Settings -> Safari -> Extensions -> Toggle "Orbot" to "on/green" state. There's no way around that. Apple added that feature, but it obviously does also want to make it hard for users to find it, so not too many make use of it.

3. You'll then will need to add rules yourself inside Orbot -> Content Blocker with the help of the rule editor.

Yes. This thing lacks a lot of features, like exporting/importing block lists. It's a little gimmick, nothing more. If you need a real add blocker, install on from the App Store. 

E.g. [Firefox Focus](https://apps.apple.com/us/app/firefox-focus-privacy-browser/id1055677337) comes with a Content Blocker, which you might like!
