### ISSUE TITLE
Orbie on with different color (orange?) for onion-only mode

### ISSUE THREAD

**Issue by tladesignz** [guardianproject/orbot-apple#37]
Currently implementing Orbie in Orbot Apple.

@cstiens, can you please provide another Orbie version (when it's on) which is suitable for onion-only mode?

Thank you!

**Comment by cstiens** [comment]
@tladesignz Here's one to use for now. I may want to change it later after giving it more thought.

![orbie-onion-only](https://user-images.githubusercontent.com/1434597/202527714-fcaed8dc-9bc4-4f62-9da3-edf8412be7a7.svg)

**Comment by tladesignz** [comment]
This is great, thank you!
