### ISSUE TITLE
UX Architecture

### ISSUE THREAD

**Issue by cstiens** [guardianproject/orbot-apple#38]
<img width="810" alt="Screenshot 2022-11-16 at 9 35 13 AM" src="https://user-images.githubusercontent.com/1434597/202224236-bd6cb7c2-aaee-4aba-b7c0-3928ed34f20b.png">

@tladesignz the padding on the 'My Tor Connection' should be the 16 pt that is standard on iOS. This mockup was pulled from the Android version that has different screen dimensions.

**Comment by tladesignz** [comment]
@cstiens, regarding UI:

- Should we force the app in dark mode, always or should we support both bright mode/dark mode?
- Colours. I assume to use system colours regarding text and background, but I currently have the following accent colours on record. Which of them are still going to be valid and which should be removed/changed?
  - DarkPurple: 3F2B4F
  - DarkGreen: 669901
  - BrightGreen: CCFF2A
  - BackgroundColor: 4F3663 (I guess I drop this one now and replace background with system colours?)
- What about the app icon? Should that stay or should Orbie become the star of the icon? If so, please provide!

**Comment by cstiens** [comment]
> Should we force the app in dark mode, always or should we support both bright mode/dark mode?

To start, let's force dark mode.

> Colours

Here are the colors used in the UI:

<img width="699" alt="Screenshot 2022-11-17 at 12 32 13 PM" src="https://user-images.githubusercontent.com/1434597/202529196-9fe99d32-22f7-4fb4-a479-8794932258c9.png">

For the Blacks, Black 1 is used as the background for primary views. For sheets/full or partial view modals (https://developer.apple.com/design/human-interface-guidelines/components/presentation/sheets), Black 2 is used for the background color. Let me know if you need more guidance from there, or if you can tell which colors are used in the UI from looking at it or pulling them from the Figma file.

> What about the app icon? Should that stay or should Orbie become the star of the icon? If so, please provide!

We have one we're using on Android that stars Orbie. I don't have it right now, but we can get it.

**Comment by tladesignz** [comment]
>> What about the app icon? Should that stay or should Orbie become the star of the icon? If so, please provide!
> We have one we're using on Android that stars Orbie. I don't have it right now, but we can get it.

https://github.com/guardianproject/orbot-apple/issues/42

**Comment by tladesignz** [comment]
> Here are the colors used in the UI:

@cstiens, in your color table image, `Black 2` and `Black 3` are *visually* different, but the hex codes provided are the same. That seems wrong...

**Comment by cstiens** [comment]
Oh that's a mistake. Black 3 is #3E3745
