### ISSUE TITLE
Add a directory for design assets

### ISSUE THREAD

**Issue by cstiens** [guardianproject/orbot-apple#40]
@tladesignz Here are the svg files for Orbie. Will you create a folder in the repo for design assets. I don't seem to have the permissions to.

[orbie_nov2022.zip](https://github.com/guardianproject/orbot-apple/files/10034522/orbie_nov2022.zip)

**Comment by tladesignz** [comment]
Finally, Xcode directly supports SVGs!

So, you can find them in the code in the different `*.imageset` folders: https://github.com/guardianproject/orbot-apple/tree/main/Shared/Assets.xcassets
