### ISSUE TITLE
Provide Orbie App Icon

### ISSUE THREAD

**Issue by tladesignz** [guardianproject/orbot-apple#42]
- 1024 x 1024 pixel
- PNG or SVG
- **no rounded corners**!

**Comment by tladesignz** [comment]
@n8fr8, I cannot assign Carrie. Can you add her to the project?

**Comment by n8fr8** [comment]
![ic_launcher-playstore](https://user-images.githubusercontent.com/30851/207899876-5e66991b-e209-49f9-b79d-fe07d1edc0c2.png)

**Comment by n8fr8** [comment]
hmmm, that is a bit lofi

**Comment by n8fr8** [comment]
![ic_launcher](https://user-images.githubusercontent.com/30851/207900117-edf87627-199d-4344-8bc4-cb62f944aa58.png)

**Comment by n8fr8** [comment]
I'm not sure that is the official icon anyhow... I will add Carrie.

**Comment by tladesignz** [comment]
Yeah. Sorry. This totally doesn't fill the spec and I really doubt it will look good, after Xcode did it's resizing, edge cutting and what-not magic.
