### ISSUE TITLE
Orbot leaves my VPN settings turned off when it exits

### ISSUE THREAD

**Issue by johnwgoodin** [guardianproject/orbot-apple#50]
I’ve discovered a possible issue with Orbot and was wondering if anyone already knows how to resolve it. I’m already filtering my home WiFi traffic manually via Settings - WiFi - WiFi Settings - DNS - Configure DNS - Manual - 176.103.130.130, 176.103.130.131 to send all my DNS requests via AdGuard Encrypted DNS so my home network would be protected.  I was looking for something like this that could send all of my DNS requests via AdGuard Encrypted DNS while I was connected to free public WiFi. I discovered DNSCloak to send all of my DNS queries via AdGuard. It sets up a DNS connection via a VPN. It works just fine until I launch Orbot and then it changes over to the Orbot VPN. Only problem with this is once I disconnect from Orbot it leaves my VPN in a turned off state. I go into Settings - VPN only to find that it’s been turned off. I have to manually turn it back on and then toggle DNSCloak back on as my VPN service. Is there any way / workaround to have Orbot restore your previous VPN connection when it exits? Is there anything I can change to my DNSCloak settings to make it prevent this from happening? Would be nice if DNSCloak could automatically handle this issue and manually turn the VPN service back on and default back to DNSCloak.

**Comment by tladesignz** [comment]
Hey, @johnwgoodin, thanks for this interesting report!

I just played around a bit:

What we can do, is *disable* the Orbot VPN piece on stop. That will automatically re-*enable* the last one used.

However, this will only restart automatically, if it has a "Connect On Demand" setting, which is also toggled on.

Orbot has no access to other profiles and cannot start other "VPNs". So, that's the best what we can do for you.

In case DNSCloak doesn't provide a "Connect On Demand" feature, you'll have to talk to them.

Stay patent. A configuration option to handle this will be contained in the next version of Orbot!
