### ISSUE TITLE
Delete Blackberry STUN Server

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot-apple#52]
This one: stun:stun.voip.blackberry.com:3478

Tor Browser hasn't used it in some time: https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/commit/fc89e8b10c3ff30db2079b2fb327d05b2b5f3c80

https://github.com/guardianproject/orbot/pull/805

**Comment by bitmold** [comment]
How would you feel about keeping a default list of STUN Servers in IPtProxy. On the one hand it's kind of annoying to build that big binary whenever the legit servers go up/down, but on the other hand these STUN servers haven't ever changed *that* much over time, and there's some definitely appealing to me about making the change in **one** place and having it propagate across Orbot Android, Orbot Apple, whatever other software...

**Comment by bitmold** [comment]
> IDK. This is very Tor-specific, whereas IPtProxy is very non-Tor specific

That makes s lot of sense, thanks

**Comment by tladesignz** [comment]
Fixed for iOS: https://github.com/tladesignz/IPtProxyUI-ios/commit/08f2bcedec491afc7442d06642e7244ec8322cd3
