### ISSUE TITLE
[Bug] Orbot not working under iOS 16.5

### ISSUE THREAD

**Issue by x-industries-uk** [guardianproject/orbot-apple#64]
I currently use Orbot as my main proxy on my iPhone SE (2nd Generation), running iOS 16.5.

However, for a few weeks now, it has completely failed to connect to Tor every time, apart from last Friday (for some reason). I have tried a number of methods to correct this, including disabling other VPNs, changing my DNS provider, trying a different WiFi network, changing Orbot's settings, and eventually even reinstalling Orbot.

I also attempted to use Orbot with Onion Browser, which worked last Friday (reason unknown), but never worked again.

You can view a recording I took of the issue on PeerTube: https://tube.tchncs.de/w/bMHCpTBm46f284hUYJEy7p

Bear in mind that, despite what it may look like, I only tap the start button once.

**Comment by x-industries-uk** [comment]
UPDATE: Cleaning the cache seems to have fixed it, but this is still not an ideal situation.

I suggest adding a setting to clear the cache on startup.

**Comment by jimscard** [comment]
I see the same phenomenon too. I'd recommend clearing the cache prior to starting a new connection to Tor, i.e., when the Start button is clicked (or similar action via API), since the problem reoccurs when stopping the connection and starting again with the app still open...

**Comment by tladesignz** [comment]
Thanks for letting me know! We're working on this problem: #67.

**Comment by tladesignz** [comment]
https://twitter.com/tladesignz/status/1672202386310307840
