### ISSUE TITLE
Create Cuban Spanish Locale

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot-apple#73]

**Comment by tladesignz** [comment]
I added Cuban Spanish to the project and prefilled it with the normal Spanish translation.
@ingfabby, do you want me to push that to Transifex, too? I didn't do that, yet. Do you want a clean slate or do you want to have it prefilled and just edit changes?

The language in Transifex is here:

https://app.transifex.com/otf/orbot-ios/language/es_CU/

I couldn't add you to it, there. Do you manage yourself or should I make someone at LocLab take care of it?

**Comment by ingfabby** [comment]
Yes, please do add it to Transifex too prefilled with standard Spanish, Thanks!

**Comment by tladesignz** [comment]
> Yes, please do add it to Transifex too prefilled with standard Spanish, Thanks!

Done. Ignore the empty txt files. That's for the app store. There's no Cuban localization of the app store.
