### ISSUE TITLE
Orbot iOS disconnects after ~1min and cannot reconnect unless clearing cache

### ISSUE THREAD

**Issue by manphiz** [guardianproject/orbot-apple#74]
iPhone 12 Pro iOS 16.6 (20G75), Orbot iOS Version 1.6.1, Build 36

Similar to [1].  I think the fix mentioned [2] is in the work, though it's not working reliably here.  As soon as the Orbot connection is disrupted, all reconnect attempts will fail after a few seconds with no additional log.  This includes automatic reconnect and manual reconnect (manually stop and connect).  Have to clear cache and retry which will succeed.

Hopefully this is not a common issue, but this potentially gives people false impression that Orbot is working while it may have already been disconnected and stuck in a retry loop.  Onion browser will stop working when Orbot disconnects so at least I know it happens when it does.  Please let me know if more info is needed for debugging.

[1] https://github.com/OnionBrowser/OnionBrowser/issues/433
[2] https://github.com/OnionBrowser/OnionBrowser/issues/433#issuecomment-1620487121

**Comment by tladesignz** [comment]
I hear your cries. So sorry. The Tor network obviously changed seriously in the last months making the client consume more and more RAM which makes it run into the imposed (by Apple) 50 MB RAM limit. It spikes especially when starting with a cache.

I now added cache clearing before starting up always on iOS. Version 1.6.2 due for release soon!

**Comment by manphiz** [comment]
> I hear your cries. So sorry. 

Not at all.  We are grateful for your hard work!

> The Tor network obviously changed seriously in the last months making the client consume more and more RAM which makes it run into the imposed (by Apple) 50 MB RAM limit. It spikes especially when starting with a cache.
> 

Thanks for the explanation!  This is interesting, and why I'm not surprised by such a low limit because, Apple.

> I now added cache clearing before starting up always on iOS. Version 1.6.2 due for release soon!

\o/ thanks again for all your hard work!
