### ISSUE TITLE
Bug on iOS 17.1

### ISSUE THREAD

**Issue by SiNaPsEr0x** [guardianproject/orbot-apple#82]
Keep restarting the tunnel is only hard for a short time, to be fixed

**Comment by tladesignz** [comment]
Yeah. I know. *sigh* 😔

We're cornered from too many sides. Apple lets us only use 50 MB of memory (on devices, which have at least 3 GB available!), Tor Project continuously adds features to increase security and reliability which use more memory and the network fluctuates daily through attacks coming and going and through changes in the amount of nodes available which also impacts memory consumption of the client.

I already explained other aspects and details here:

https://github.com/guardianproject/orbot-apple/issues/79#issuecomment-1748365503
https://github.com/OnionBrowser/OnionBrowser/issues/443#issuecomment-1764187964
https://github.com/guardianproject/orbot-apple/issues/81#issuecomment-1776909258


The latest Onion Browser has a Tor client built in again, which you can use with iOS 17 and up. That is not memory constrained and might work more reliably for you.

At least, if it's just about web browsing.


Sorry. 🤷

**Comment by SiNaPsEr0x** [comment]
Thanks

**Comment by kn0wmad** [comment]
> Yeah. I know. _sigh_ 😔
> 
> We're cornered from too many sides. Apple lets us only use 50 MB of memory (on devices, which have at least 3 GB available!), Tor Project continuously adds features to increase security and reliability which use more memory and the network fluctuates daily through attacks coming and going and through changes in the amount of nodes available which also impacts memory consumption of the client.
> 
> I already explained other aspects and details here:
> 
> [#79 (comment)](https://github.com/guardianproject/orbot-apple/issues/79#issuecomment-1748365503) [OnionBrowser/OnionBrowser#443 (comment)](https://github.com/OnionBrowser/OnionBrowser/issues/443#issuecomment-1764187964) [#81 (comment)](https://github.com/guardianproject/orbot-apple/issues/81#issuecomment-1776909258)
> 
> The latest [Onion Browser](https://onionbrowser.com) has a Tor client built in again, which you can use with iOS 17 and up. That is not memory constrained and might work more reliably for you.
> 
> At least, if it's just about web browsing.
> 
> Sorry. 🤷

Will this project be discontinued?  Do you have other ideas of how to proxy app traffic via Tor?
