### ISSUE TITLE
Issue on orbot ios 1.6.6

### ISSUE THREAD

**Issue by saeedmirzaeigit** [guardianproject/orbot-apple#83]
The latest release of orbot ios Version 1.6.6 build 43 not working and stuck and flicker when pressing start button! I tried various fixes like clearing cache or changing connection method or removing vpn profile and even reinstalling orbot again, it seems that orbot  stuck in loop and don’t go next step. Checked on iphone 11 family, 13 family and se 2 family Version 1.6.6 build 43

**Comment by saeedmirzaeigit** [comment]
By reseting network setting , the issue is fixed

**Comment by tladesignz** [comment]
It's... difficult.

More background info here: https://github.com/guardianproject/orbot-apple/issues/82#issuecomment-1789631432


I'm sorry. 🤷
