### ISSUE TITLE
Failure to Connect or Disconnects from Tor

### ISSUE THREAD

**Issue by chriso22** [guardianproject/orbot-apple#84]
I have noticed that my Orbot app fails to connect(hangs up at during connecting) or disconnects while in use. This is a new issue that has occurred recently.

Currently on iOS 17.1.1 (recent update)and Orbot 1.6.6, build 43.

**Comment by tladesignz** [comment]
Yeah. Sorry. It's... difficult. You can read about it here: (Follow the links.)

https://github.com/guardianproject/orbot-apple/issues/82#issuecomment-1789631432
